name = "ProxyInterfaces"
uuid = "9b3bf0c4-f070-48bc-ae01-f2584e9c23bc"
authors = ["Sahm Stephan <stephan.sahm@gmx.de>"]
version = "1.0.1"

[compat]
julia = "1"

[extras]
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Suppressor"]
