name = "ProxyInterface"
uuid = "90c4b210-f34a-11e9-1a87-5d0d3aaf0cab"
authors = ["Sahm Stephan <stephan.sahm@gmx.de>"]
version = "1.0.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

[compat]
Compat = "2.1, 3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
